tarkov/tarkov/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('tarkovdb/', include('tarkovdb.urls')),
    path('',include('tarkovdb.urls')),
    path('admin/', admin.site.urls),
]

tarkov/tarkovdb/urls.py
from django.urls import path

from . import views

app_name = 'tarkovdb'

urlpatterns = [
    # ex: /polls/
    path('all', views.index, name='index'),
    path('maps', views.maps, name='maps'),
    path('',views.add,name='add'),
    path('<int:item_id>/', views.detail, name='detail'),

]

tarkov/tarkovdb/models.py
from django.db import models


class Item(models.Model):
    price = models.IntegerField(default=0)
    name = models.CharField(max_length=100)
    def __str__ (self):
    	return self.name
    	
    def expensive(self):
    	if(self.price > 1000000):
    		return "Yah"
    	else:
    		return "Nah"

tarkov/tarkovdb/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.http import HttpResponse
from .models import Item
from django.template import RequestContext
from django.template import loader
from .scrape import scrape


def index(request):
    item_list = Item.objects.order_by('-price')[:15]
    template = loader.get_template('tarkovdb/index.html')
    context = {
        'item_list': item_list,
    }
    return render(request,'tarkovdb/index.html',context)

def detail(request, item_id):
    item = get_object_or_404(Item,pk=item_id)
    return render(request, 'tarkovdb/detail.html', {'item': item})

def add(request):
	if request.method == "POST":
		n = request.POST.get('Item name', 'Did not work')
		pr = scrape(n)
		i = Item(name=n,price=pr)
		i.save()
	return render(request,'tarkovdb/test.html')

def maps(request):
		template = loader.get_template('tarkovdb/maps.html')
		return render(request,'tarkovdb/maps.html')

tarkov/templates/tarkovdb/detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Tarkov Database Index</title>
  </head>
  <body>
<h1>{{ item.name }}</h1>
<ul>
	This item costs {{item.price}} rubles
</ul>

  	 <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

tarkov/templates/tarkovdb/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Tarkov Database Index</title>
  </head>
  <body>

{% if item_list %}
    <ul>
    {% for item in item_list %}
        <li><a href="{% url 'tarkovdb:detail' item.id %}">{{ item.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Items are available.</p>
{% endif %}



  	 <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

tarkov/templates/tarkovdb/maps.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Tarkov Maps</title>
  </head>
  <body>
    <h1>Shoreline</h1>
    <img src="https://img.resized.co/dexerto/eyJkYXRhIjoie1widXJsXCI6XCJodHRwczpcXFwvXFxcL2ltYWdlcy5kZXhlcnRvLmNvbVxcXC91cGxvYWRzXFxcLzIwMjBcXFwvMDFcXFwvMDcxMDU4MTVcXFwvRXNjYXBlLWZyb20tVGFya292LVNob3JlbGluZS1tYXAtYW5kLWV4dHJhY3Rpb24tcG9pbnRzLTEwMjR4NTc2LmpwZ1wiLFwid2lkdGhcIjpcIlwiLFwiaGVpZ2h0XCI6XCJcIixcImRlZmF1bHRcIjpcImh0dHBzOlxcXC9cXFwvczMtZXUtd2VzdC0xLmFtYXpvbmF3cy5jb21cXFwvcHBsdXMuaW1hZ2VzLmRleGVydG8uY29tXFxcL3VwbG9hZHNcXFwvMjAxOVxcXC8xMVxcXC8xMTIxNDk0M1xcXC9wbGFjZWhvbGRlci5qcGdcIn0iLCJoYXNoIjoiNDgzNmVhY2MwNzcwYWYzNTdiOWFiZDJlZjc2YmJmMDRkYzNmZGZlNyJ9/escape-from-tarkov-shoreline-map-and-extraction-points-1024x576.jpg">
    <h1>Customs</h1>
    <img src=" https://img.resized.co/dexerto/eyJkYXRhIjoie1widXJsXCI6XCJodHRwczpcXFwvXFxcL2ltYWdlcy5kZXhlcnRvLmNvbVxcXC91cGxvYWRzXFxcLzIwMjBcXFwvMDFcXFwvMDcxMDQ4MDhcXFwvRXNjYXBlLWZyb20tVGFya292LUN1c3RvbXMtbWFwLWFuZC1leHRyYWN0aW9uLXBvaW50cy0xMDI0eDU3Ni5wbmdcIixcIndpZHRoXCI6XCJcIixcImhlaWdodFwiOlwiXCIsXCJkZWZhdWx0XCI6XCJodHRwczpcXFwvXFxcL3MzLWV1LXdlc3QtMS5hbWF6b25hd3MuY29tXFxcL3BwbHVzLmltYWdlcy5kZXhlcnRvLmNvbVxcXC91cGxvYWRzXFxcLzIwMTlcXFwvMTFcXFwvMTEyMTQ5NDNcXFwvcGxhY2Vob2xkZXIuanBnXCJ9IiwiaGFzaCI6Ijg1YzJjYTVkMzhjNTJhYWJhOGFjOGViZmIxODJkMTM1ODdjMjU1NzMifQ==/escape-from-tarkov-customs-map-and-extraction-points-1024x576.png">
    <h1>Interchange</h1>
    <img src="https://img.resized.co/dexerto/eyJkYXRhIjoie1widXJsXCI6XCJodHRwczpcXFwvXFxcL2ltYWdlcy5kZXhlcnRvLmNvbVxcXC91cGxvYWRzXFxcLzIwMjBcXFwvMDFcXFwvMDcxMDQ1MjlcXFwvRXNjYXBlLWZyb20tVGFya292LUludGVyY2hhbmdlLW1hcC1hbmQtZXh0cmFjdGlvbi1wb2ludHMtMTAyNHg2MzcuanBnXCIsXCJ3aWR0aFwiOlwiXCIsXCJoZWlnaHRcIjpcIlwiLFwiZGVmYXVsdFwiOlwiaHR0cHM6XFxcL1xcXC9zMy1ldS13ZXN0LTEuYW1hem9uYXdzLmNvbVxcXC9wcGx1cy5pbWFnZXMuZGV4ZXJ0by5jb21cXFwvdXBsb2Fkc1xcXC8yMDE5XFxcLzExXFxcLzExMjE0OTQzXFxcL3BsYWNlaG9sZGVyLmpwZ1wifSIsImhhc2giOiI2M2U3Mzc3YWRhNzljNjcxNTQwNjU1ZDZlNjZkNzBhZDE3ZDNhZTMyIn0=/escape-from-tarkov-interchange-map-and-extraction-points-1024x637.jpg">
    <h1>Woods</h1>
    <img src="https://img.resized.co/dexerto/eyJkYXRhIjoie1widXJsXCI6XCJodHRwczpcXFwvXFxcL2ltYWdlcy5kZXhlcnRvLmNvbVxcXC91cGxvYWRzXFxcLzIwMjBcXFwvMDFcXFwvMDcxMDUyMjJcXFwvRXNjYXBlLWZyb20tVGFya292LVdvb2RzLW1hcC1hbmQtZXh0cmFjdGlvbi1wb2ludHMtMTAyNHg3NTEuanBnXCIsXCJ3aWR0aFwiOlwiXCIsXCJoZWlnaHRcIjpcIlwiLFwiZGVmYXVsdFwiOlwiaHR0cHM6XFxcL1xcXC9zMy1ldS13ZXN0LTEuYW1hem9uYXdzLmNvbVxcXC9wcGx1cy5pbWFnZXMuZGV4ZXJ0by5jb21cXFwvdXBsb2Fkc1xcXC8yMDE5XFxcLzExXFxcLzExMjE0OTQzXFxcL3BsYWNlaG9sZGVyLmpwZ1wifSIsImhhc2giOiI3ZmNlNzE2YTZiMTNmNWVjMzdiYTMyY2JjMzNjNjE4YjQ0ZGM1OWVmIn0=/escape-from-tarkov-woods-map-and-extraction-points-1024x751.jpg">






<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

tarkov/templates/tarkovdb/test.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Tarkov Database Web App</title>
  </head>
  <body>
  	<h1>This is the page to add items</h1>
  	 <li><a href="{% url 'tarkovdb:index' %}">List of Items in DataBase</a></li>
     <li><a href="{% url 'tarkovdb:maps' %}">Maps Page</a></li>

    <form method="post">
    	{% csrf_token %} 
      <div class="form-group">
         <label for='Item name'> Item name: </label>
         <input type='text' name='Item name' id='username'> <br><br>
      </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>




  	 <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>